### ISSUE TITLE
ERROR: GDAL >= 3.5 is required for rasterio. Please upgrade GDAL.

### ISSUE THREAD

**Issue by balacmi** [odtp-org/odtp-eqasim#23]
When I run and prepare execution using the odtp-eqasim component with the Corsica scenario, I get the following error when `rasterio` is being installed:

ERROR: GDAL >= 3.5 is required for rasterio. Please upgrade GDAL.

Detailed log file can be found here:

[eqasim_error.txt](https://github.com/user-attachments/files/17644276/eqasim_error.txt)

Any ideas how to solve this issue? Not sure where GDAL version is set in the whole process.

Btw, this happens for both v0.4.3 and v0.4.5 of the component. I did not try the other ones.

**Comment by caviri** [comment]
Hello @balacmi, 

It seems there's a problem building the dependencies. This should be a third-party dependency not fixed cause we have specific versions for each one. GDAL was required by rasterio, that if I remember correctly was required by geopandas. 

The GDAL version is specified in the Dockerfile but the 3.5 is not available for this Ubuntu. I achieved a successful building by using `rasterio==1.3.8` in requirements.txt. But I didn't test a full run yet. 

``` requirements.txt
matplotlib==3.7.2
rasterio==1.3.8
pandas==2.0.3
scipy==1.11.1
numpy==1.23.5
geopandas==0.13.2
numba==0.57.1
palettable==3.3.3
scikit-learn==1.3.0
shapely==2.0.1
tqdm==4.65.0
tables==3.8.0
xlrd==2.0.1
openpyxl==3.1.2
pip==22.0.2
simpledbf==0.2.6
synpp==1.5.1
python-levenshtein==0.12.1
pytest==7.4.0
xlwt==1.3.0
pysal==23.1
py7zr==0.20.5
```

I'm going to try to rebuild the image on my machine and then upload the image to docker.hub so the component will be fixed and this kind of errors avoided.

**Comment by balacmi** [comment]
Thank you @caviri! I will wait for the update.

**Comment by caviri** [comment]
Hi @balacmi, Good news. 

I released some new versions of all the components related. I modified the `requirements.txt` so all the dependencies are fixes and compatible with `amd64` and `arm64` architecture. This involved mainly to fix `rasterio` and `fiona` to an specific version. Now the building and running are working at least for the Corsica case of use.  

Also I updated the DT repository for corsica https://github.com/odtp-org/dt-corsica-mobility. This repository contains an script to run the DT with ODTP or a `docker-compose.yml` to run the whole pipeline without ODTP, just docker. The link to the initial dataset is there too. However, you need to configure the secrets file with a password that I'll send you in private.

I think that it would be great if we can have an open small dataset to perform automatic testing of the pipeline in github.

Let me know if this works for you.

**Comment by balacmi** [comment]
This works, thank you @caviri !
